### ISSUE TITLE
error map

### ISSUE THREAD

**Issue by xianghuix** [ElsevierSoftwareX/SOFTX-D-17-00061#4]
Dear developers,

   I tried this package and found it is very useful. I however have one question about the error map generated from correlation operations. When I performed some 3D correlation on two sets of data sets, I found there are quite few interior pixels have error value 32.0. I dug into the code a little and found value 32.0 indicates 'don't have enough data (i.e. +- 1 px) to do a CC interpolation'. May you please explain a little bit more why this happens and what users should do to remove the errors in the calculations?

Thanks,
XH

**Comment by vivlet** [comment]
Dear Xianghuix,

the author of the code is Erika available at https://github.com/erikatudisco, please refer to her for technical issue.

**Comment by erikatudisco** [comment]
Hej Xianghuix,

The error 32 is given, for instance, when the highest CC is found in the edges of the area of search in the second image (i.e., the search window). In this case the subpixel refinement can not be performed because it needs one pixel extra.
The cause for this to happen is generally a too small search window but it can also be due to poor correlation. If only few pixel in your volume are affected by this error it is not probable that the cause is the search window (as normally near points move together). I suggest then that you perform again the analysis only on those data (use the option  
"prior file" and "Use points from prior" with "2 <= error <= 32" (as in section 5.2 of the manual) and using the "Image interpolator translation" as subpixel refinement mode.

I hope this answer your question. Don't esitate to contact me again for any other questions or issues.

Best regards,
Erika Tudisco

Assistant Professor
Division of Geotechnical Engineering, Lund University, Lund, Sweden

Postal Address:
  Geotechnical Engineering
  Dept. of Construction Sciences
  Faculty of Engineering
  Lund University
  P.O. Box 118
  SE-221 00 Lund, Sweden

E-mail: erika.tudisco@construction.lth.se
Web: http://www.geoteknik.lth.se/personal/tudisco-erika/
Tel: +46 46 22 20 356
